build_dev:
  image: node:16
  script:
    - npm install
    - npm run build --mode dev
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - dev

deploy_dev:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ root@13.212.103.56:/var/www/html/
  only:
    - dev


build_prod:
  image: node:16
  script:
    - npm install
    - npm run build --mode prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

deploy_prod:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ root@13.212.103.56:/var/www/html/
  only:
    - master
